eureka:
  client:
    serviceUrl:
      defaultZone: http://rstyro:rstyropwd@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: springcloud-config-client
  profiles:
    active: dev
    
---
spring:
  profiles: dev

server:
  port: 7700

info:
    state: dev
    name: info-dev-name
    desc: info-dev-desc

---
spring:
  profiles: test
  name: test

server:
  port: 7701

info:
    state: test
    name: info-test-name
    desc: info-test-desc

---
spring:
  profiles: prd
  name: prd

server:
  port: 7702

info:
    state: prd
    name: info-prd-name
    desc: info-prd-desc